services:
  - type: web
    name: plagix-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        value: your_django_secret_key_here
      - key: OPENAI_API_KEY
        value: your_openai_key_here
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
