# Generated by Django 5.2.3 on 2025-06-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_comparisonhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonhistory',
            name='match_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
